<?php
/**
 * @var $this Decidir\AdminPlanesCuotas\Block\Adminhtml\PlanPago\Container
 */
?>
<div class="page-main-actions">
    <div class="page-actions-placeholder"></div>
    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <button id="" title="Back" type="button"
                        class="action-default scalable action-back"
                        onclick="setLocation('<?= $this->getUrl('adminplanescuotas/planpago/admin')?>')">
                    <span><?= __('Back') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>

<div class="adminplanes-loader" style="display: none"></div>

<div data-bind="scope: 'form_plan_pago'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "form_plan_pago": {
                        "component": "Decidir_AdminPlanesCuotas/js/plan_pago/form",
                        "template" : "Decidir_AdminPlanesCuotas/plan_pago/form"
                    }
                }
            }
        }
    }
</script>

<script type="text/javascript">

    require([
        "jquery"
    ], function($)
    {
        jQuery(document).ready(function() {

            console.log('asdadad 224234');

            // validate the comment form when it is submitted
//        jQuery("#commentForm").validate();

            // validate signup form on keyup and submit
//            jQuery("#plan-pago-form").validate({
//                rules: {
//                    plan_nombre: "required"
//                },
//                messages: {
//                    plan_nombre: "Please enter your firstname"
//                }
            });

    });

//    jQuery.validator.setDefaults({
//        submitHandler: function() {
//            alert("submitted!");
//        }
//    });

//    jQuery(document).ready(function() {
//
//        console.log('asdadad 224234');
//
//        // validate the comment form when it is submitted
////        jQuery("#commentForm").validate();
//
//        // validate signup form on keyup and submit
//        jQuery("#plan-pago-form").validate({
//            rules: {
//                plan_nombre: "required"
//            },
//            messages: {
//                plan_nombre: "Please enter your firstname"
//            }
//        });

        // propose username by combining first- and lastname
//        jQuery("#username").focus(function() {
//            var firstname = $("#firstname").val();
//            var lastname = $("#lastname").val();
//            if (firstname && lastname && !this.value) {
//                this.value = firstname + "." + lastname;
//            }
//        });

        //code to hide topic selection, disable for demo
//        var newsletter = $("#newsletter");
//        // newsletter topics are optional, hide at first
//        var inital = newsletter.is(":checked");
//        var topics = $("#newsletter_topics")[inital ? "removeClass" : "addClass"]("gray");
//        var topicInputs = topics.find("input").attr("disabled", !inital);
//        // show when newsletter is checked
//        newsletter.click(function() {
//            topics[this.checked ? "removeClass" : "addClass"]("gray");
//            topicInputs.attr("disabled", !this.checked);
//        });
//    });

</script>