<?php
/**
 * @var $this Decidir\AdminPlanesCuotas\Block\Adminhtml\PlanPago\Container
 *
 **/
?>
<script type="text/javascript">
    window.adminPlanesCuotasConfig = new Object();
    window.adminPlanesCuotasConfig.tarjetas = <?= \Zend_Json::encode($this->getTarjetas()) ?>;
    window.adminPlanesCuotasConfig.bancos   = <?= \Zend_Json::encode($this->getBancos()) ?>;
    window.adminPlanesCuotasConfig.dias     = <?= \Zend_Json::encode($this->getDias()) ?>;
    window.adminPlanesCuotasConfig.admin_url= "<?= $this->getUrl('adminplanescuotas/planpago/admin')?>";
    window.adminPlanesCuotasConfig.save_url = "<?= $this->getUrl('adminplanescuotas/planpago/save')?>";
    window.adminPlanesCuotasConfig.plan_pago= false;
    window.adminPlanesCuotasConfig.cuotas   = false;
    window.adminPlanesCuotasConfig.promocionesCarrito   = <?= \Zend_Json::encode($this->getPromocionesCarrito()) ?>;
</script>
